create table if not exists public.categorias_servicos (
  id text primary key,
  nome text not null,
  ativo boolean not null default true,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.servicos (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nome text not null,
  descricao text not null default '',
  preco text not null default '',
  categoria_id text references public.categorias_servicos(id) on update cascade on delete set null,
  ativo boolean not null default true,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_categorias_servicos_updated_at on public.categorias_servicos;
create trigger set_categorias_servicos_updated_at
before update on public.categorias_servicos
for each row execute function public.set_updated_at();

drop trigger if exists set_servicos_updated_at on public.servicos;
create trigger set_servicos_updated_at
before update on public.servicos
for each row execute function public.set_updated_at();

insert into public.categorias_servicos (id, nome, ativo, ordem)
select
  item->>'id' as id,
  coalesce(nullif(item->>'label', ''), item->>'id') as nome,
  coalesce((item->>'active')::boolean, true) as ativo,
  ordinality::integer as ordem
from public.configuracao c
cross join lateral jsonb_array_elements(
  case
    when jsonb_typeof(c.valor->'items') = 'array' then c.valor->'items'
    when jsonb_typeof(c.valor) = 'array' then c.valor
    else '[]'::jsonb
  end
) with ordinality as cats(item, ordinality)
where c.chave = 'categorias'
on conflict (id) do update set
  nome = excluded.nome,
  ativo = excluded.ativo,
  ordem = excluded.ordem;

insert into public.servicos (id, slug, nome, descricao, preco, categoria_id, ativo, ordem)
select
  nullif(item->>'id', '')::bigint as id,
  item->>'slug' as slug,
  coalesce(nullif(item->>'name', ''), item->>'slug') as nome,
  coalesce(item->>'desc', '') as descricao,
  coalesce(item->>'price', '') as preco,
  nullif(item->>'category', '') as categoria_id,
  true as ativo,
  ordinality::integer as ordem
from public.configuracao c
cross join lateral jsonb_array_elements(c.valor) with ordinality as services(item, ordinality)
where c.chave = 'servicos'
  and jsonb_typeof(c.valor) = 'array'
  and item ? 'slug'
on conflict (id) do update set
  slug = excluded.slug,
  nome = excluded.nome,
  descricao = excluded.descricao,
  preco = excluded.preco,
  categoria_id = excluded.categoria_id,
  ativo = excluded.ativo,
  ordem = excluded.ordem;

select setval(
  pg_get_serial_sequence('public.servicos', 'id'),
  coalesce((select max(id) from public.servicos), 1),
  true
);
