-- O esquema herdado, reconstruido a partir do codigo.
--
-- POR QUE ESTA MIGRACAO EXISTE
--
-- O banco original foi perdido em 08/2026. Das 10 tabelas que o codigo usa, as
-- migracoes desta pasta criavam UMA (`webhook_eventos`) e alteravam duas: as
-- outras sete vieram do `Aplicativo-FULL` e da era n8n, criadas fora de migracao,
-- e so existiam dentro do Supabase. Sem elas versionadas, o repositorio nao
-- reconstruia o proprio ambiente — e foi exatamente isso que doeu.
--
-- Esta migracao fecha esse buraco. Ela cria as NOVE tabelas que faltavam
-- (`webhook_eventos` continua sendo criada pela migracao 20260730140000, logo
-- adiante) e vem datada ANTES de todas as outras, para que a cadeia inteira rode
-- na ordem certa num banco vazio:
--
--   20260730120000  esta aqui        -> cria as 9 tabelas herdadas
--   20260730140000  webhook_eventos  -> cria a 10a
--   20260730160000  dados_cliente    -> unique no telefone + default em created_at
--   20260730180000  dados_cliente    -> renomeia nomewpp -> nome
--   20260730180100  webhook_eventos  -> acao text -> text[]
--   20260730190000  agenda_prof.     -> janela 7..15 -> 4..10
--
-- A data (30/07) e ORDENACAO, nao arqueologia: as tabelas sao bem mais velhas que
-- isso. O que a data diz e "antes da primeira migracao que ja existia aqui".
--
-- DE ONDE VEIO CADA COLUNA
--
-- Nao houve dump. Cada coluna foi derivada lendo as consultas que a tocam:
-- `CALENDARIO/server.js` (26 rotas), `BARBEARIA/src/db/*.ts` e as proprias
-- migracoes seguintes. Onde o SQL do app tinha cast explicito (`hora_inicio::text`,
-- `dia_marcado::text`, `data::text`) o tipo e certo; no resto e o mais provavel.
-- O levantamento completo, com as incertezas nomeadas uma a uma, esta em
-- `AUDITORIA/02-BANCO.md`. Ler de la antes de tratar qualquer tipo aqui como
-- verdade absoluta.
--
-- ESTADO PRE-MIGRACOES, DE PROPOSITO
--
-- Tres coisas aqui parecem erradas e nao sao — elas reproduzem o estado ANTERIOR
-- as migracoes que vem depois, para que aquelas migracoes continuem fazendo o que
-- dizem que fazem em vez de virarem no-op:
--
--   1. `dados_cliente.nomewpp` com esse nome (a 20260730180000 renomeia);
--   2. `dados_cliente` sem unique no telefone e sem default em created_at
--      (a 20260730160000 poe os dois);
--   3. `agenda_profissional` com a janela em 7..15 (a 20260730190000 baixa p/ 4..10).
--
-- Resistir a "consertar" isso aqui. Migracao que se antecipa a propria historia
-- transforma as seguintes em enfeite.
--
-- RLS
--
-- Cada tabela sai com RLS LIGADO e ZERO POLITICAS — o mesmo que `webhook_eventos`
-- faz, e pela mesma razao: nega tudo pela API publica (`anon`/`authenticated`) em
-- silencio, enquanto bot e API entram por conexao direta, que ignora RLS.
--
-- No banco antigo isso acontecia sozinho, por um event trigger (`ensure_rls`) que
-- e hardening de plataforma, NAO configuracao nossa. Num Supabase novo ele pode
-- nao estar la, e num Postgres comum (container, Neon, RDS) ele nao existe. Por
-- isso o `enable row level security` vai explicito: o que era acidente vira
-- decisao, e o comportamento passa a ser o mesmo em qualquer host.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. profissionais — os barbeiros
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.profissionais (
  id          bigint      generated by default as identity primary key,
  nome        text        not null,
  cor         text,
  ativo       boolean     not null default true,
  created_at  timestamptz not null default now()
);

comment on table public.profissionais is
  'Os barbeiros da barbearia. Baixa e SOFT delete: DELETE /profissionais/:id so poe ativo=false.';
comment on column public.profissionais.cor is
  'Cor hex do barbeiro na agenda do painel (ex.: #8b5cf6). O front cai em #888888 quando nula.';
comment on column public.profissionais.ativo is
  'false some da lista inteira: some da pergunta do bot e deixa de valer como resposta dele.';

-- O bot le `where ativo is true order by id` — ordem de cadastro, estavel. Ordenar
-- por nome faria a lista se reorganizar sozinha quando alguem corrigisse um cadastro.
create index if not exists profissionais_ativos on public.profissionais (id) where ativo;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. servicos — o catalogo
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.servicos (
  id            bigint  generated by default as identity primary key,
  slug          text,
  nome          text    not null,
  descricao     text,
  preco         numeric(10,2),
  categoria_id  bigint,
  ativo         boolean not null default true,
  ordem         integer
);

comment on column public.servicos.preco is
  'INCERTO: numeric(10,2) e inferencia. Nenhuma consulta do codigo revela a escala real — se aparecer dump, conferir antes de confiar.';
comment on column public.servicos.categoria_id is
  'Aponta para uma tabela `categorias` que NAO existe aqui: o codigo le a coluna e nunca a usa. Sem FK de proposito. Candidata a ser apagada.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. agenda_profissional — a configuracao de agenda de cada barbeiro (1:1)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.agenda_profissional (
  profissional_id         bigint  primary key
                            references public.profissionais (id) on delete cascade,
  dias_semana             jsonb   not null default '[1,2,3,4,5,6]'::jsonb,
  hora_inicio             time    not null default '08:00',
  hora_fim                time    not null default '19:00',
  duracao_min             integer not null default 60,
  intervalo_inicio        time,
  intervalo_duracao_min   integer,
  janela_agendamento_dias integer default 10,
  atualizado_em           timestamptz,
  -- 7..15 e o valor ANTIGO. A 20260730190000 baixa para 4..10 (teto de linhas de
  -- uma lista do WhatsApp). Ver o cabecalho: estado pre-migracoes de proposito.
  constraint agenda_profissional_janela_agendamento_dias_check
    check (janela_agendamento_dias >= 7 and janela_agendamento_dias <= 15)
);

comment on table public.agenda_profissional is
  'Um registro por profissional (PK = FK). Sem registro, a API usa DEFAULT_AGENDA de server.js.';
comment on column public.agenda_profissional.dias_semana is
  'jsonb com inteiros: 0=Dom ... 6=Sab. Ex.: [1,2,3,4,5,6] = segunda a sabado.';
comment on column public.agenda_profissional.intervalo_inicio is
  'Comeco do almoco/pausa. Nulo = sem intervalo. Anda junto com intervalo_duracao_min.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. dias_bloqueados — folgas e bloqueios pontuais
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.dias_bloqueados (
  id              bigint generated by default as identity primary key,
  profissional_id bigint not null
                    references public.profissionais (id) on delete cascade,
  data            date   not null,
  motivo          text,
  periodos        text[],
  created_at      timestamptz not null default now(),
  constraint dias_bloqueados_prof_data_unico unique (profissional_id, data)
);

comment on column public.dias_bloqueados.periodos is
  'Subconjunto de {morning,afternoon,night}. NULO = dia inteiro — e a API grava NULO quando os tres sao marcados (server.js:1066), porque "os tres" e "o dia todo" sao o mesmo estado.';

-- O unique (profissional_id, data) nao e enfeite: e o alvo do
-- `on conflict (profissional_id, data) do update` que a API usa para bloquear e
-- reajustar um dia sem consultar antes.
create index if not exists dias_bloqueados_prof_data
  on public.dias_bloqueados (profissional_id, data);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. agendamentos — o registro do atendimento
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.agendamentos (
  id            bigint generated by default as identity primary key,
  telefone      text,
  cliente       text   not null,
  profissional  text   not null,
  servico       text,
  dia_marcado   date   not null,
  hora_marcada  time   not null,
  status        text   not null default 'confirmado',
  source        text            default 'app-etapas',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz
);

comment on table public.agendamentos is
  'Um atendimento marcado. Vai ser podado um dia — por isso o nome do cliente tambem mora em dados_cliente, que nao e podado.';
comment on column public.agendamentos.profissional is
  'O NOME do barbeiro, texto sem FK. Decisao travada em REGRAS.md (2026-07-30): todo JOIN do sistema e `a.profissional = p.nome`. Preco disso: renomear um barbeiro orfana os agendamentos dele em silencio, e o nome NUNCA pode ser digitado — tem que vir da tabela profissionais.';
comment on column public.agendamentos.status is
  'agendado | confirmado | concluido | cancelado | reagendado. Contam como horario OCUPADO: agendado, reagendado, confirmado (BOOKED_STATUSES em server.js:73).';
comment on column public.agendamentos.source is
  'De onde veio a marcacao: app-etapas (padrao da API), presencial (encaixe no balcao), ou o bot.';

create index if not exists agendamentos_dia_hora
  on public.agendamentos (dia_marcado, hora_marcada);
create index if not exists agendamentos_prof_dia
  on public.agendamentos (profissional, dia_marcado);
-- Serve o GET /agendamentos/verificar-telefone, que o bot usa a cada conversa.
create index if not exists agendamentos_telefone
  on public.agendamentos (telefone);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. dados_cliente — o cadastro de contato do bot (herdada do n8n)
-- ─────────────────────────────────────────────────────────────────────────────
-- Ver o cabecalho: `nomewpp`, sem unique e sem default em created_at sao o estado
-- PRE-migracoes. As duas seguintes (160000 e 180000) arrumam os tres pontos.
create table if not exists public.dados_cliente (
  id          bigint generated by default as identity primary key,
  telefone    text,
  nomewpp     text,
  created_at  timestamptz
);

comment on table public.dados_cliente is
  'Cadastro do contato. Sobrevive a poda de agendamentos: o cliente que volta depois nao precisa repetir o nome.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 7-9. O CRM do WhatsApp — espelho da conversa no painel do dono
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.whatsapp_contacts (
  id                   bigint generated by default as identity primary key,
  phone                text not null unique,
  wa_id                text,
  name                 text,
  last_message_at      timestamptz,
  service_window_until timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz
);

comment on column public.whatsapp_contacts.phone is
  'Formato canonico: wa_id da Cloud API, digitos puros com DDI (ex.: 553399990011). UNIQUE — e o alvo do on conflict do espelho.';
comment on column public.whatsapp_contacts.service_window_until is
  'Fim da janela de 24h da Meta. Conta da ULTIMA mensagem do CLIENTE (inbound), nao da resposta. Ver ANEXO_WHATSAPP_META.';
comment on column public.whatsapp_contacts.name is
  'Nome do PERFIL do WhatsApp, que a Meta manda de graca. NAO serve para chamar o cliente — para isso e dados_cliente.nome.';

create table if not exists public.whatsapp_conversations (
  id              bigint generated by default as identity primary key,
  contact_id      bigint not null
                    references public.whatsapp_contacts (id) on delete cascade,
  status          text   not null default 'open',
  assigned_to     text,
  last_message_at timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);

comment on column public.whatsapp_conversations.status is
  'open | bot | human | closed. A conversa fecha quando a janela de 24h vence; a mensagem seguinte abre outra.';

create index if not exists whatsapp_conversations_contato
  on public.whatsapp_conversations (contact_id);
-- Ordem da lista do painel: `order by last_message_at desc nulls last`.
create index if not exists whatsapp_conversations_recentes
  on public.whatsapp_conversations (last_message_at desc nulls last);

create table if not exists public.whatsapp_messages (
  id                  bigint generated by default as identity primary key,
  conversation_id     bigint not null
                        references public.whatsapp_conversations (id) on delete cascade,
  contact_id          bigint not null
                        references public.whatsapp_contacts (id) on delete cascade,
  direction           text   not null,
  sender_type         text   not null,
  whatsapp_message_id text,
  message_type        text,
  body                text,
  media_id            text,
  status              text,
  raw_payload         jsonb,
  created_at          timestamptz not null default now(),
  received_at         timestamptz,
  read_at             timestamptz
);

comment on column public.whatsapp_messages.direction is
  'inbound (cliente falou) | outbound (barbearia falou).';
comment on column public.whatsapp_messages.sender_type is
  'customer | bot | human | system. `human` e o que faz o bot calar: donoAtendendo() em src/db/eventos.ts le exatamente esta coluna.';
comment on column public.whatsapp_messages.whatsapp_message_id is
  'O wamid da Meta. UNIQUE parcial: e o que impede a mensagem duplicada no painel quando o espelho reenvia.';

-- Parcial porque mensagem escrita pelo painel ainda nao tem wamid no instante do insert.
create unique index if not exists whatsapp_messages_wamid_unico
  on public.whatsapp_messages (whatsapp_message_id)
  where whatsapp_message_id is not null;

-- Serve as duas consultas quentes do painel: a thread aberta e o LEFT JOIN LATERAL
-- que busca a ultima mensagem de cada conversa da lista.
create index if not exists whatsapp_messages_conversa_recente
  on public.whatsapp_messages (conversation_id, created_at desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS — ligado sem politica em todas. Ver o cabecalho.
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.profissionais           enable row level security;
alter table public.servicos                enable row level security;
alter table public.agenda_profissional     enable row level security;
alter table public.dias_bloqueados         enable row level security;
alter table public.agendamentos            enable row level security;
alter table public.dados_cliente           enable row level security;
alter table public.whatsapp_contacts       enable row level security;
alter table public.whatsapp_conversations  enable row level security;
alter table public.whatsapp_messages       enable row level security;

-- rollback:
--   drop table if exists public.whatsapp_messages;
--   drop table if exists public.whatsapp_conversations;
--   drop table if exists public.whatsapp_contacts;
--   drop table if exists public.dados_cliente;
--   drop table if exists public.agendamentos;
--   drop table if exists public.dias_bloqueados;
--   drop table if exists public.agenda_profissional;
--   drop table if exists public.servicos;
--   drop table if exists public.profissionais;
