-- As duas tabelas que o modal "Configurações do site" precisa, e a ligação que
-- `servicos.categoria_id` esperava desde a reconstrução do banco.
--
-- O modal foi construído pelo Victor sobre o mundo de teste (`VITE_MOCK=1`) e o
-- contrato está em `docs/superpowers/specs/2026-09-27-configuracoes-site-agendamento.md`.
-- As rotas não existiam no servidor: a tela respondia "Não foi possível carregar as
-- configurações do site" assim que passou a rodar contra o banco real (29/09/2026).
--
-- ── categorias_servicos ──────────────────────────────────────────────────────
--
-- O contrato identifica a categoria por um SLUG que a tela gera a partir do nome
-- ("Cabelo" -> `cabelo`). Ele é único por loja, não no sistema: duas barbearias podem
-- ter, cada uma, a sua "Cabelo". Daí o `unique (barbearia_id, slug)`.
--
-- O `id` numérico continua existindo porque é ele que `servicos.categoria_id` já
-- referenciava. A API fala em slug; o banco liga por id. A tradução acontece nas rotas.
--
-- ── A chave composta, e por que não uma FK simples ───────────────────────────
--
-- `servicos (categoria_id, barbearia_id) -> categorias_servicos (id, barbearia_id)`.
--
-- Com FK simples em `categoria_id`, um serviço da loja A poderia apontar para uma
-- categoria da loja B — o banco aceitaria, e a vitrine de A mostraria o rótulo de B.
-- Nada impediria isso além do código lembrar de conferir. Com a barbearia dentro da
-- chave, o banco recusa. É o mesmo princípio do papel `app_api` sem bypass: a defesa
-- que não depende de ninguém lembrar.
--
-- `on delete set null (categoria_id)` — a forma com lista de colunas, Postgres 15+.
-- Sem a lista, apagar a categoria anularia também `barbearia_id`, que é `not null`, e
-- o delete falharia. A rota recusa apagar categoria com serviço ATIVO; os inativos só
-- perdem a referência.
--
-- ── configuracoes_site ───────────────────────────────────────────────────────
--
-- Uma linha por barbearia, e só quando o dono salvou alguma coisa. Sem linha, a rota
-- responde valores padrão com o nome da própria barbearia — então não há backfill, e
-- uma loja nova tem página inicial desde o primeiro minuto.

create table if not exists public.categorias_servicos (
  id bigint generated by default as identity primary key,
  barbearia_id bigint not null references public.barbearias (id),
  slug text not null,
  rotulo text not null,
  ativa boolean not null default true,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  constraint categorias_servicos_slug_por_barbearia unique (barbearia_id, slug),
  -- Alvo da chave composta de `servicos`. Redundante como unicidade (o `id` já é
  -- único), necessário como referência.
  constraint categorias_servicos_id_barbearia unique (id, barbearia_id)
);

alter table public.servicos
  add constraint servicos_categoria_da_mesma_barbearia
  foreign key (categoria_id, barbearia_id)
  references public.categorias_servicos (id, barbearia_id)
  on delete set null (categoria_id);

create table if not exists public.configuracoes_site (
  barbearia_id bigint primary key references public.barbearias (id),
  titulo_linha1 text not null default 'Bem-vindo à',
  nome_destaque text not null,
  texto_botao text not null default 'Agendar',
  filtro_categorias boolean not null default true,
  atualizado_em timestamptz not null default now()
);

-- RLS explícito: o event trigger `ensure_rls` não existe neste projeto.
alter table public.categorias_servicos enable row level security;
alter table public.configuracoes_site enable row level security;

create policy categorias_servicos_da_barbearia on public.categorias_servicos
  for all to authenticated
  using (barbearia_id = public.barbearia_atual())
  with check (barbearia_id = public.barbearia_atual());

create policy configuracoes_site_da_barbearia on public.configuracoes_site
  for all to authenticated
  using (barbearia_id = public.barbearia_atual())
  with check (barbearia_id = public.barbearia_atual());

-- rollback:
--   drop policy configuracoes_site_da_barbearia on public.configuracoes_site;
--   drop policy categorias_servicos_da_barbearia on public.categorias_servicos;
--   drop table public.configuracoes_site;
--   alter table public.servicos drop constraint servicos_categoria_da_mesma_barbearia;
--   drop table public.categorias_servicos;
