-- A tabela que faltava para o sistema ser multi-tenant: `barbearias`.
--
-- Ate aqui o sistema atendia UMA barbearia, e isso nao estava escrito em lugar
-- nenhum — estava implicito no fato de nenhuma tabela ter dono. O discriminador ja
-- CHEGAVA (`webhook_eventos.numero_barbearia`, o `phone_number_id` que a Meta manda),
-- era gravado desde o primeiro dia, e nunca era lido. Esta migracao e o comeco de
-- transformar aquele dado morto em chave.
--
-- Tres colunas merecem explicacao:
--
-- `whatsapp_phone_number_id` — o mesmo valor que chega em `metadata.phone_number_id`
-- no webhook. E o unico dado que a Meta entrega capaz de dizer QUAL barbearia recebeu
-- a mensagem, entao ele e a chave de resolucao do bot. UNIQUE porque dois cadastros
-- apontando pro mesmo numero fariam a resolucao virar sorteio. NULLABLE porque a
-- barbearia existe antes de ter numero: no auto-servico da versao final, o dono cria
-- a conta e paga antes de qualquer coisa da Meta estar pronta.
--
-- `slug` — o identificador da barbearia no site de agendamento, e tambem o que as
-- rotas publicas da API vao exigir para saber de que loja estao falando. NOT NULL
-- porque uma barbearia sem slug e uma barbearia inalcancavel pelo cliente.
--
-- `user_id` — o login do dono, em `auth.users`. NULLABLE porque nesta rodada o
-- cadastro e manual: a linha da barbearia nasce antes de existir usuario. UNIQUE
-- porque e o que garante que `barbearia_atual()` (Fase 2) devolva uma linha so — uma
-- funcao de contexto que pode devolver duas e uma politica de RLS que nao decide nada.
--
-- ponytail: um login por barbearia. Teto: o dono e a unica pessoa com acesso ao
-- painel. Gatilho de upgrade: o primeiro pedido de segundo login (socio, gerente,
-- recepcao) troca `user_id` por uma tabela `barbearia_usuarios` com papel.

create table if not exists public.barbearias (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text not null unique,
  whatsapp_phone_number_id text unique,
  user_id uuid unique references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

-- RLS ligado explicitamente, e nao por conta do event trigger `ensure_rls`. O motivo
-- esta inteiro em 20260828120000: aquele trigger e hardening do projeto Supabase
-- ANTIGO, nao existe no atual, e confiar nele deixou `webhook_eventos` aberta sem
-- ninguem notar. Onde o trigger existir, isto e no-op.
--
-- Continua SEM POLITICA nesta migracao: as politicas sao a Fase 2, e escreve-las agora
-- seria enfeite — quem conecta hoje e `postgres`, que tem `rolbypassrls`.
alter table public.barbearias enable row level security;

-- A loja que ja existe. O `phone_number_id` e o unico valor distinto hoje em
-- `webhook_eventos.numero_barbearia`, conferido no banco antes de escrever isto — e o
-- mesmo que esta no `WHATSAPP_PHONE_NUMBER_ID` do `.env`.
--
-- `on conflict do nothing` no slug: reaplicar a cadeia num banco que ja tem a loja nao
-- pode duplicar. O registro em `schema_migrations` ja impediria, mas esta e a linha da
-- qual TODO o backfill seguinte depende — vale o cinto alem do suspensorio.
insert into public.barbearias (nome, slug, whatsapp_phone_number_id)
values ('Barbearia Lucas Costa', 'lucas-costa', '922642447599728')
on conflict (slug) do nothing;

-- rollback:
--   drop table public.barbearias;
